#! /bin/bash

: ${SAUCE_USER:?"Need to set SAUCE_USER:

    export SAUCE_USER=<your sauce username>"}
: ${SAUCE_KEY:?"Need to set SAUCE_API_KEY:

    export SAUCE_KEY=<your sauce api key>"}

COMMAND=0

if [ "$1" == "update" ] ; then
    COMMAND=1
    killall java -u $LOGNAME
    sleep 10
    rm -rf $HOME/sauceConnect
    cd
    mkdir $HOME/sauceConnect
    cd $HOME/sauceConnect
    curl http://saucelabs.com/downloads/Sauce-Connect-latest.zip -o sauce-connect-latest.zip
    unzip sauce-connect-latest.zip
    rm sauce-connect-latest.zip
fi

if [ "$1" == "restart" ] ; then
    COMMAND=1
    killall java -u $LOGNAME
    sleep 20
    nohup /usr/bin/java -jar $HOME/sauceConnect/Sauce-Connect.jar --shared-tunnel $SAUCE_USER $SAUCE_KEY > $HOME/$SAUCE_USER &
fi

if [ "$1" == "crontab" ] ; then
    COMMAND=1
    (echo "MAILTO=\"\"

00 20 * * * rm $HOME/sauce_connect.log $HOME/$SAUCE_USER > /dev/null
00 20 * * * $HOME/sauce restart
01 20 * * * $HOME/sauce status

") | crontab
fi

if [ "$1" == "status" ] ; then
    COMMAND=1

    echo "Running Sauce Tunnels:"
    ps aux | grep Sauce | grep -v grep


    echo "
Current Crontab:"
    (crontab -l) | cat
fi

HELP="Usage: ./sauce COMMAND
Control your Sauce tunnel. I use this only on a dedicated Sauce Connect
box, as _crontab_ overwrites the crontab with only Sauce Connect
entries, and _restart_ indiscriminately kills all java processes. These
behaviors can of course be modified if necessary.

The commands you can use are:

   crontab      Write over the crontab with the default Sauce-tasks
                only crontab

   help         Show this help

   restart      Kill all java processes belonging to the user and
                nohup the sauce tunnel, stdout redirected to
                $HOME/$SAUCE_USER

   status       Reconstruct the crontab, view the running Sauce
                tunnels and the current crontab

   update       Download a new version of the Sauce Connect jar in
                ~/sauceConnect. You'll want to run ./sauce restart
                after this to start the tunnel again
"

if [ "$1" == "help" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ $COMMAND -eq 0 ] ; then
    echo "$HELP" > $HOME/README
    echo "$HELP"
fi
