#! /bin/bash

: ${SAUCE_USERNAME:?"Need to set SAUCE_USERNAME:

    export SAUCE_USERNAME=<your sauce username>"}
: ${SAUCE_ACCESS_KEY:?"Need to set SAUCE_ACCESS_KEY:

    export SAUCE_ACCESS_KEY=<your sauce api key>"}
MAIL=your@email.com
COMMAND=0
SAUCE_VERSION=sc-4.3.5-linux

if [ "$1" == "update" ] ; then
    COMMAND=1
    killall java -u $LOGNAME
    sleep 10
    rm -rf $HOME/sauceConnect
    cd
    mkdir $HOME/sauceConnect
    cd $HOME/sauceConnect
    SC=sc.tar.gz
    curl https://saucelabs.com/downloads/$SAUCE_VERSION.tar.gz -o $SC
    tar -xvf $SC
    rm $SC
fi

if [ "$1" == "restart" ] ; then
    COMMAND=1
    echo "Killing all sc processes belonging to $LOGNAME and waiting for them to shut down";
    killall -u $LOGNAME sc
    rm $HOME/sauce_connect.log > /dev/null 2>&1
    sleep 5
    ulimit -n 8000 > /dev/null 2>&1
    CMD="nohup $HOME/sauceConnect/$SAUCE_VERSION/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY --shared-tunnel"
    echo "Starting a new tunnel with

$CMD";
    $CMD > $HOME/$SAUCE_USERNAME 2>&1 &
fi

if [ "$1" == "crontab" ] ; then
    COMMAND=1
    (echo "MAILTO=\"$MAIL\"

00 20 * * * rm $HOME/sauce_connect.log $HOME/$SAUCE_USERNAME > /dev/null
00 7,12,17,20 * * * $HOME/sauce restart > /dev/null
01 7,12,17,20 * * * $HOME/sauce status > /dev/null
*/10 * * * * $HOME/sauce monitor > /dev/null

") | crontab
fi

if [ "$1" == "status" ] ; then
    COMMAND=1
    TUNNEL=$(curl --silent --insecure https://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@saucelabs.com/rest/v1/$SAUCE_USERNAME/tunnels)
    echo "Sauce Tunnel Status: $TUNNEL"

    echo "
Running Sauce Tunnels on this box:"
    ps -ef | grep [s]auceConnec

    echo "
Current Crontab:"
    (crontab -l) | cat
fi

if [ "$1" == "monitor" ] ; then
    COMMAND=1
    TUNNEL=$(curl --silent --insecure https://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@saucelabs.com/rest/v1/$SAUCE_USERNAME/tunnels)
    echo "$(date): $TUNNEL" >> $HOME/monitor_log
fi

HELP="Usage: ./sauce COMMAND
Control your sauce tunnel.

The commands you can use are:

   help         Show this help

   restart      Kill all java processes belonging to the user and
                nohup the sauce tunnel, stdout redirected to
                $HOME/$SAUCE_USERNAME

   crontab      Write over the crontab with the default Sauce-tasks
                only crontab

   status       View the running Sauce tunnels and the current crontab

   update       Download a new version of the Sauce Connect jar in
                ~/sauceConnect. You'll want to run ./sauce restart
                after this to start the tunnel again

   monitor      Check the status and echo it to a file in the home dir
"

if [ "$1" == "help" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ $COMMAND -eq 0 ] ; then
    echo "$HELP"
fi
